# PANDAS and NUMPY
How to handle data - data exploration, data cleaning, data engineering required for Data Science

In [2]:
import numpy as np
import pandas as pd

# NUMPY

# https://numpy.org/

PERFORMANT
The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

In [1]:
import numpy as np


In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [5]:
a.dtype.type

numpy.int32

In [6]:
a.size

15

In [16]:
type(a)

numpy.ndarray

In [18]:
b = np.array([[6,7,8],[9,10,11]])

In [7]:
b = np.array([[10,11,12],[14,15,16]])

In [8]:
b.shape


(2, 3)

In [9]:
b.size

6

In [10]:
b.dtype

dtype('int32')

In [11]:
b

array([[10, 11, 12],
       [14, 15, 16]])

In [12]:
c = np.array([(1.2,3.4,5.2), (7,8,10)])

In [13]:
c

array([[ 1.2,  3.4,  5.2],
       [ 7. ,  8. , 10. ]])

In [14]:
c.dtype

dtype('float64')

# The function zeros creates an array full of zeros

In [44]:
d = np.zeros((3,4))

In [45]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# The function ones - creates an array full of ones

In [15]:
e=np.ones((3,4))

In [16]:
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# The function empty 

In [17]:
f = np.empty((2,4))

In [18]:
f

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.16991405e-321, 7.56599806e-307,
        8.90104238e-307]])

# Print and RESHAPE function

In [19]:
g = np.arange(12)

In [20]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
print(g.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
g.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
g.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
g.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [40]:
print(g.reshape(6,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [28]:
print(g.reshape(3,2,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [43]:
#print(g.reshape(2,3,2))

In [30]:
b

array([[10, 11, 12],
       [14, 15, 16]])

In [31]:
c

array([[ 1.2,  3.4,  5.2],
       [ 7. ,  8. , 10. ]])

In [27]:
b.shape

(2, 3)

In [29]:
c.shape

(2, 3)

In [32]:
b+c

array([[11.2, 14.4, 17.2],
       [21. , 23. , 26. ]])

In [33]:
b-c

array([[8.8, 7.6, 6.8],
       [7. , 7. , 6. ]])

In [34]:
c-b

array([[-8.8, -7.6, -6.8],
       [-7. , -7. , -6. ]])

In [35]:
b*c ##elementwise multiplication

array([[ 12. ,  37.4,  62.4],
       [ 98. , 120. , 160. ]])

In [36]:
np.add(b,c)

array([[11.2, 14.4, 17.2],
       [21. , 23. , 26. ]])

In [100]:
np.sqrt(c)

array([[1.09544512, 1.84390889, 2.28035085],
       [2.64575131, 2.82842712, 3.16227766]])

In [37]:
np.square(c)

array([[  1.44,  11.56,  27.04],
       [ 49.  ,  64.  , 100.  ]])

In [38]:
np.round_(c)

array([[ 1.,  3.,  5.],
       [ 7.,  8., 10.]])

In [39]:
np.exp(c)

array([[3.32011692e+00, 2.99641000e+01, 1.81272242e+02],
       [1.09663316e+03, 2.98095799e+03, 2.20264658e+04]])

In [40]:
b.shape

(2, 3)

In [41]:
c.shape

(2, 3)

In [59]:
## Recall matrix multiplication

In [47]:
b.shape

(2, 3)

In [48]:
d.shape

(3, 4)

In [61]:
##Here is one exmaple

In [50]:
k = b@d

In [51]:
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
k.shape

(2, 4)

In [58]:
d.shape

(3, 4)

In [54]:
b@d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Random number generator - random() function

In [3]:
h = np.random.random_sample((5,2))


In [4]:
l = np.random.random_sample((3,4))

In [5]:
h.shape

(5, 2)

In [6]:
h

array([[0.31817782, 0.66307187],
       [0.52541306, 0.52163656],
       [0.93431217, 0.80106959],
       [0.8476229 , 0.37359513],
       [0.3648866 , 0.0298522 ]])

In [7]:
h.min()

0.02985220080647555

In [8]:
h.max()

0.9343121658332714

In [9]:
h.sum()

5.3796379113839

In [10]:
h

array([[0.31817782, 0.66307187],
       [0.52541306, 0.52163656],
       [0.93431217, 0.80106959],
       [0.8476229 , 0.37359513],
       [0.3648866 , 0.0298522 ]])

In [11]:
h.sum(axis=0)

array([2.99041256, 2.38922535])

In [12]:
h.sum(axis=1)

array([0.98124969, 1.04704963, 1.73538176, 1.22121803, 0.3947388 ])

In [13]:
h.std(axis=0)

array([0.25033122, 0.26543037])

In [14]:
h.std(axis=1)

array([0.17244703, 0.00188825, 0.06662129, 0.23701389, 0.1675172 ])

# Indexing, Slicing and Iterating


In [65]:
h

array([[0.7613513 , 0.59405937],
       [0.00882519, 0.19933056],
       [0.78336269, 0.92969025],
       [0.95003044, 0.87588577],
       [0.03372778, 0.09245768]])

In [66]:
h[2]

array([0.78336269, 0.92969025])

In [67]:
h[4]

array([0.03372778, 0.09245768])

In [68]:
h[4][0]

0.033727775884743516

In [69]:
h[0][0]

0.7613513045624339

In [113]:
##Print 0.493106 - X41

In [70]:
h[0:1]

array([[0.7613513 , 0.59405937]])

In [71]:
h[0:1] = 10

In [72]:
h

array([[1.00000000e+01, 1.00000000e+01],
       [8.82518844e-03, 1.99330557e-01],
       [7.83362692e-01, 9.29690250e-01],
       [9.50030444e-01, 8.75885766e-01],
       [3.37277759e-02, 9.24576754e-02]])

In [73]:
h[0] = 100

In [74]:
h

array([[1.00000000e+02, 1.00000000e+02],
       [8.82518844e-03, 1.99330557e-01],
       [7.83362692e-01, 9.29690250e-01],
       [9.50030444e-01, 8.75885766e-01],
       [3.37277759e-02, 9.24576754e-02]])

In [134]:
h[0][0] = 323.00

In [135]:
h

array([[3.23000000e+02, 1.00000000e+02],
       [7.02829269e-01, 7.07088028e-01],
       [8.36590470e-01, 5.63197620e-01],
       [7.46481300e-01, 4.93106370e-01],
       [1.04837299e-01, 7.13288859e-01]])

In [75]:
h[-1]

array([0.03372778, 0.09245768])

In [76]:
h[-2]

array([0.95003044, 0.87588577])

In [78]:
h[1,...]

array([0.00882519, 0.19933056])

In [145]:
h[...,1]

array([100.        ,   0.70708803,   0.56319762,   0.49310637,
         0.71328886])

In [79]:
h[:,1]

array([1.00000000e+02, 1.99330557e-01, 9.29690250e-01, 8.75885766e-01,
       9.24576754e-02])

In [80]:
for i in h:
    print(i)

[100. 100.]
[0.00882519 0.19933056]
[0.78336269 0.92969025]
[0.95003044 0.87588577]
[0.03372778 0.09245768]


In [81]:
for element in h.flat:
    print(element)

100.0
100.0
0.008825188443479015
0.19933055741286887
0.7833626920731704
0.929690250270487
0.9500304435760759
0.8758857655510832
0.033727775884743516
0.09245767541837291


# manipulation of SHAPE of numpy array 

In [153]:
rng = np.random.default_rng(5)
k = np.floor(10 * rng.random((3,4)))

In [154]:
k

array([[8., 8., 5., 2.],
       [0., 3., 4., 0.],
       [0., 9., 6., 2.]])

In [157]:
j=k.ravel()

In [159]:
j.shape

(12,)

In [160]:
j

array([8., 8., 5., 2., 0., 3., 4., 0., 0., 9., 6., 2.])

In [162]:
for i in j:
    print(i)

8.0
8.0
5.0
2.0
0.0
3.0
4.0
0.0
0.0
9.0
6.0
2.0


In [161]:
j.reshape(3,4)

array([[8., 8., 5., 2.],
       [0., 3., 4., 0.],
       [0., 9., 6., 2.]])

In [164]:
j.reshape(4,3)

array([[8., 8., 5.],
       [2., 0., 3.],
       [4., 0., 0.],
       [9., 6., 2.]])

In [165]:
##What other combinations we can have?

# Stacking together two different array

In [171]:
b.shape

(2, 3)

In [172]:
c.shape

(2, 3)

In [176]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [177]:
c

array([[ 1.2,  3.4,  5.2],
       [ 7. ,  8. , 10. ]])

In [174]:
l = np.vstack((b,c))

In [178]:
l

array([[ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [ 1.2,  3.4,  5.2],
       [ 7. ,  8. , 10. ]])

In [180]:
m = np.hstack((b,c))

In [181]:
m

array([[ 6. ,  7. ,  8. ,  1.2,  3.4,  5.2],
       [ 9. , 10. , 11. ,  7. ,  8. , 10. ]])

# COPY np.arrays

In [182]:
n = m

In [183]:
m is n

True

# Deep copy

In [184]:
p = n.copy()

In [185]:
p

array([[ 6. ,  7. ,  8. ,  1.2,  3.4,  5.2],
       [ 9. , 10. , 11. ,  7. ,  8. , 10. ]])

Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

Questions
all, any, nonzero, where

Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

Basic Statistics
cov, mean, std, var

Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot