In [1]:
#import necessary base packages
import numpy as np
import pandas as pd
import scipy
import sklearn

In [2]:
import pandas
attri_data = pd.read_csv('E:/Book_Revision/attri_data_10.txt', sep=',', header=0)
print(attri_data)

   Attrition  Yrs_Exp Work_Challenging Work_Envir Compensation Tech_Exper
0        Yes      2.5               No        Low          Low  Excellent
1         No      2.0              Yes  Excellent    Excellent  Excellent
2         No      2.5              Yes  Excellent          Low  Excellent
3        Yes      2.0               No  Excellent          Low  Excellent
4         No      2.0              Yes        Low          Low        Low
5        Yes      2.0               No        Low          Low  Excellent
6         No      2.0               No  Excellent    Excellent        Low
7        Yes      2.5               No        Low    Excellent  Excellent
8        Yes      2.0               No  Excellent          Low  Excellent
9        Yes      3.0              Yes        Low    Excellent  Excellent
10       Yes      3.5               No  Excellent          Low  Excellent
11        No      3.0              Yes  Excellent    Excellent  Excellent
12        No      2.0              Yes

In [3]:
#get full information on attri_data dataframe
X=attri_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
Attrition           52 non-null object
Yrs_Exp             52 non-null float64
Work_Challenging    52 non-null object
Work_Envir          52 non-null object
Compensation        52 non-null object
Tech_Exper          52 non-null object
dtypes: float64(1), object(5)
memory usage: 2.5+ KB


In [4]:
#making a copy of the attri_data dataframe
X = attri_data.copy()

In [5]:
#labelEncode categorical variables out of the predictor variables 
#This is required in order that the LogisticRegression model 
#builder recognizes the values of these predictors
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[['Attrition','Work_Challenging','Work_Envir','Compensation',
   'Tech_Exper']]=X[['Attrition','Work_Challenging','Work_Envir',
   'Compensation','Tech_Exper']].apply(le.fit_transform)
X.head(5)

Attrition  Yrs_Exp  Work_Challenging  Work_Envir  Compensation  Tech_Exper
0          1      2.5                 0           1             1           0
1          0      2.0                 1           0             0           0
2          0      2.5                 1           0             1           0
3          1      2.0                 0           0             1           0
4          0      2.0                 1           1             1           1

In [6]:
#split the dataframe with response variables (y)
#and another with only the predictor #variables (X)
y = X.Attrition
X = X[X.columns[1::]]

In [7]:
#split the dataset into two separate sets viz. training set
#and test set manually 
#training set for generating the model
#test set for validating the model generated
train_samp = (40)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
    train_size=train_samp, test_size=12)

In [8]:
from sklearn.linear_model import LogisticRegression
logist_regre = LogisticRegression(random_state = 0, penalty = 'l2', 
    solver = 'lbfgs', multi_class = 'multinomial', 
    max_iter = 500).fit(X_train, y_train)

In [9]:
# Using logist_regre model
sparsity_1 = np.mean(logist_regre.coef_ == 0) * 100
score_1 = logist_regre.score(X_test, y_test)
# print('Best C % .4f' % clf.C_)
print("Sparsity with L2 penalty: %.2f%%" % sparsity_1)
print("Test score with L2 penalty: %.4f" % score_1)

Sparsity with L2 penalty: 0.00%
Test score with L2 penalty: 0.6667


In [10]:
predicted = logist_regre.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted))

             precision    recall  f1-score   support

          0       0.75      0.50      0.60         6
          1       0.62      0.83      0.71         6

avg / total       0.69      0.67      0.66        12



In [11]:
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix
print(sm.confusion_matrix(y_test, predicted))

[[3 3]
 [1 5]]


In [12]:
#Even though we did not get high accuracy above, if we iterate
#the same exercise we may not get the same accuracy, we 
#may get higher or lower accuracy
#We need to set the random seed using np if we want
#the same result to be output each time we run the step
#As we know from the discussion on the R Section, which
#we can validate through the model statistics in
#Python also, we know that Yrs_Exp is not significant
#to the model.  Let us remove the Yrs_Exp from the dataframe
#and generate the model and check for the accuracy
Z = X.drop(['Yrs_Exp'], axis=1)

In [13]:
#split the dataset into two separate sets viz. training set
#and test set manually 
#training set for generating the model
#test set for validating the model generated
train_samp = (40)
from sklearn.model_selection import train_test_split
Z_train, Z_test, y_train, y_test = train_test_split(Z, y, 
    train_size=train_samp, test_size=12)

In [14]:
from sklearn.linear_model import LogisticRegression
logist_regre = LogisticRegression(random_state = 0, penalty = 'l2', 
    solver = 'lbfgs', multi_class = 'multinomial', 
    max_iter = 500).fit(Z_train, y_train)

In [15]:
np.random.seed(10)
# Using logist_regre model
sparsity_1 = np.mean(logist_regre.coef_ == 0) * 100
score_1 = logist_regre.score(Z_test, y_test)
# print('Best C % .4f' % clf.C_)
print("Sparsity with L2 penalty: %.2f%%" % sparsity_1)
print("Test score with L2 penalty: %.4f" % score_1)

Sparsity with L2 penalty: 0.00%
Test score with L2 penalty: 0.9167


In [16]:
predicted = logist_regre.predict(Z_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, predicted))

             precision    recall  f1-score   support

          0       1.00      0.86      0.92         7
          1       0.83      1.00      0.91         5

avg / total       0.93      0.92      0.92        12



In [17]:
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix
print(sm.confusion_matrix(y_test, predicted))

[[6 1]
 [0 5]]


In [18]:
#print logistic regression coefficients
logist_regre.coef_

array([[-0.75862672,  0.96860213,  0.63232032, -0.84379994]])

In [19]:
#Seabold, Skipper, and Josef Perktold. “statsmodels: Econometric and 
#statistical modeling with python.” Proceedings of the 9th Python in 
#Science Conference. 2010. Thanks to Statsmodels
import statsmodels.api as sm
from statsmodels.formula.api import logit
logit_mod = sm.Logit(y_train, Z_train)

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [20]:
logit_resi = logit_mod.fit()
logit_resi.summary()

Optimization terminated successfully.
         Current function value: 0.262090
         Iterations 8


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:              Attrition   No. Observations:                   40
Model:                          Logit   Df Residuals:                       36
Method:                           MLE   Df Model:                            3
Date:                Sun, 14 Aug 2022   Pseudo R-squ.:                  0.6156
Time:                        11:44:08   Log-Likelihood:                -10.484
converged:                       True   LL-Null:                       -27.274
                                        LLR p-value:                 2.428e-07
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Work_Challenging    -3.0228      1.287     -2.349      0.019      -5.545      -0.501
Work_Envir           4.1816      1.637      2.554      0.011       0.973       7.390
Compensation         2.2552      1.138      1.982      0.047       0.025       4.485
Tech_Exper          -3.9206      1.735     -2.259      0.024      -7.322      -0.519
====================================================================================
"""

In [21]:
#Here, we are applying the model to the full data
#set (excluding Yrs_Exp to predict on the full dataset
predicted_full = logist_regre.predict(Z)
from sklearn.metrics import classification_report
print(classification_report(y, predicted_full))

             precision    recall  f1-score   support

          0       0.88      0.92      0.90        24
          1       0.93      0.89      0.91        28

avg / total       0.90      0.90      0.90        52



In [24]:
#confusion matrizx of the prediction on the
#full data set (except Yrs_Exp)
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix
print(sm.confusion_matrix(y, predicted_full))

[[22  2]
 [ 3 25]]


In [25]:
print(logit_resi.tvalues)

Work_Challenging   -2.349154
Work_Envir          2.554033
Compensation        1.981947
Tech_Exper         -2.259078
dtype: float64


In [26]:
print(logit_resi.pvalues)

Work_Challenging    0.018816
Work_Envir          0.010648
Compensation        0.047485
Tech_Exper          0.023879
dtype: float64
